In [ ]:
import numpy as np
import pandas as pd

In [ ]:
med_price_list = [55, 25, 75, 40, 1050, 1250]
med_list_np_array = np.array(med_price_list)
med_list_pd_np_series = pd.Series(med_list_np_array)
med_list_pd_series = pd.Series(med_price_list, index = ("Omeprazole", "Azithromycin", "Metformin", "Ibuprofen", "Ozempic", "Mounjaro"))
med_list_label_pd_series = pd.Series(med_price_list, index = ("Omeprazole", "Azithromycin", "Metformin", "Ibuprofen", "Ozempic", "Mounjaro"))
print(med_list_pd_np_series)
print(med_list_pd_series)
med_list_price_increase = med_list_pd_series * 1.025
print(med_list_price_increase)

0      55
1      25
2      75
3      40
4    1050
5    1250
dtype: int64
Omeprazole        55
Azithromycin      25
Metformin         75
Ibuprofen         40
Ozempic         1050
Mounjaro        1250
dtype: int64
Omeprazole        56.375
Azithromycin      25.625
Metformin         76.875
Ibuprofen         41.000
Ozempic         1076.250
Mounjaro        1281.250
dtype: float64

In [ ]:
student = ['Mary', 'Peter', 'Susan', 'Toby', 'Vishal']
df1 = pd.DataFrame(student, columns=['Student'])
df1

  Student
0    Mary
1   Peter
2   Susan
3    Toby
4  Vishal

In [ ]:
grades = ['B-', 'A+', 'A-', 'B+', 'C']
df2 = pd.DataFrame({'Student':student,'Grade':grades})
df2

  Student Grade
0    Mary    B-
1   Peter    A+
2   Susan    A-
3    Toby    B+
4  Vishal     C

In [ ]:
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
temp_data[:2]
temp_data[2]
temp_data[[1, 2]]
temp_data['day3']

<ipython-input-25-6a039065b825>:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp_data[2]
<ipython-input-25-6a039065b825>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp_data[[1, 2]]

30

In [ ]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]

In [ ]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1

In [ ]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })

calorie_data
calorie_data[:2]
calorie_data['calories']
calorie_data[::2]

    day  calories  duration_min
0  day1       450            30
2  day3       345            29
4  day5       600            48

In [ ]:
import pandas as pd

# Create a dataframe with a date column
df = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
    'value': [10, 20, 30]
})

# Convert the date column to datetime format
df['date'] = pd.to_datetime(df['date'])

print(df)
df['date'].dt.month

        date  value
0 2023-01-01     10
1 2023-01-02     20
2 2023-01-03     30

0    1
1    1
2    1
Name: date, dtype: int32

In [ ]:
data = {
    'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
     'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
              'Manchester', 'Cairo', 'Osaka'],
    'age': [41, 28, 33, 34, 38, 31, 37],
     'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
 }

row_labels = [101, 102, 103, 104, 105, 106, 107]
df = pd.DataFrame(data=data, index=row_labels)
print(df)
print(df.head)
print(df.head(n=2))
print(df.tail)
print(df.tail(n=1))
print(df.loc(103))

       name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0
<bound method NDFrame.head of        name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0>
       name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
<bound method NDFrame.tail of        name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0>
     name   city  age  py-score
107  Nori  Osaka   37      84.0

ValueError: No axis named 103 for object type DataFrame

In [ ]:
cities = df['city']
cities

101    Mexico City
102        Toronto
103         Prague
104       Shanghai
105     Manchester
106          Cairo
107          Osaka
Name: city, dtype: object

In [ ]:
print(df)
print(df.loc[103])
print(df.index)
print(df.columns)

       name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0
name          Jana
city        Prague
age             33
py-score      81.0
Name: 103, dtype: object
Index([101, 102, 103, 104, 105, 106, 107], dtype='int64')
Index(['name', 'city', 'age', 'py-score'], dtype='object')

In [ ]:
import pandas as pd

# Read the CSV file
from google.colab import drive
drive.mount('/content/drive')
books_data = pd.read_csv("/content/drive/MyDrive/books.csv")

# View the first 5 rows
books_data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006

In [ ]:
print(np.array([1,10,21,35,72]))

[ 1 10 21 35 72]

In [ ]:
array_1 = np.linspace(0,20,6)
print(array_1)
array_2 = np.arange(0,20,6)
print(array_2)

[ 0.  4.  8. 12. 16. 20.]
[ 0  6 12 18]

In [ ]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
print(mat)
print(np.average(mat))

[[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
131.66666666666666

In [ ]:
a = np.arange(0,20)
a[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
np.cos([0, 1, 2, 3, 4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
print(new_list)

array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
print(new_array)

[1, 2, 3, 4, 5, 6]
[5 7 9]

In [ ]:
print(np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]]))

[[9 8 7]
 [6 5 4]
 [3 2 1]]

In [ ]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
print(mat)
mat[1] = 5
print(" ")
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 2 1]
 [5 5 5]
 [1 8 9]]

In [ ]:
print(np.arange(start=1, stop=10, step=1).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
randint_matrix1 = np.random.randint(1, 10, 10).reshape(2,5)
print(randint_matrix1)
print("")
randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)

[[7 8 9 9 1]
 [6 4 7 1 2]]

[[19 18 17 16 16]
 [10 18 17 11 12]]

In [ ]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
np.dot(n1, n2)

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [ ]:
np.save("/content/drive/MyDrive/matrix1", randint_matrix1)
np.savez("/content/drive/MyDrive/matrices", randint_matrix1=randint_matrix1, randint_matrix2=randint_matrix2)

In [ ]:
loaded_arr = np.load("/content/drive/MyDrive/matrix1")
loaded_multi = np.load("content/drive/MyDrive/matrices")
print(loaded_arr)
print(loaded_multi)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/matrix1'